/**
 * SchemaGoExtractor — deterministic regex extractor for Go ORM/SQL stacks:
 *
 *  - GORM   — struct fields with `gorm:"..."` tags + `func (X) TableName()`.
 *  - sqlc   — generated structs in `*.sql.go` mirroring `CREATE TABLE` columns
 *             (we treat any struct in a sqlc-generated file as a table).
 *
 * Emits Table + Column nodes and HAS edges in the same shape as the other
 * schema extractors.
 */

import type { GraphNode, GraphRelationship } from '@ekg/shared';

export interface GoOrmExtractionResult {
  readonly tables: readonly GraphNode[];
  readonly columns: readonly GraphNode[];
  readonly relations: readonly GraphRelationship[];
}

const EMPTY: GoOrmExtractionResult = { tables: [], columns: [], relations: [] };

const GO_STRUCT_RE =
  /type\s+([A-Z][A-Za-z0-9_]*)\s+struct\s*\{([\s\S]*?)\n\}/g;
const GO_FIELD_RE =
  /^\s*([A-Z][A-Za-z0-9_]*)\s+(\*?[A-Za-z_][A-Za-z0-9_.\[\]]*)\s*(?:`([^`]*)`)?\s*$/gm;
const TABLENAME_RE =
  /func\s*\(\s*[A-Za-z_]\w*\s+\*?([A-Z][A-Za-z0-9_]*)\s*\)\s*TableName\s*\(\s*\)\s*string\s*\{[^}]*return\s+["`]([^"`]+)["`]/g;

const SQLC_FILE_HINT = '// Code generated by sqlc';

export class SchemaGoExtractor {
  static handles(content: string, relativePath?: string): boolean {
    if (relativePath && /\.sql\.go$/.test(relativePath)) return true;
    return content.includes('gorm:') || content.includes(SQLC_FILE_HINT);
  }

  extract(
    content: string,
    relativePath: string,
    repoUrl: string,
  ): GoOrmExtractionResult {
    if (!SchemaGoExtractor.handles(content, relativePath)) return EMPTY;

    const tables: GraphNode[] = [];
    const columns: GraphNode[] = [];
    const relations: GraphRelationship[] = [];

    const isSqlc = content.includes(SQLC_FILE_HINT) || /\.sql\.go$/.test(relativePath);

    // Pre-scan TableName() overrides.
    const tableNameMap = new Map<string, string>();
    TABLENAME_RE.lastIndex = 0;
    let tn: RegExpExecArray | null;
    while ((tn = TABLENAME_RE.exec(content))) {
      tableNameMap.set(tn[1]!, tn[2]!);
    }

    GO_STRUCT_RE.lastIndex = 0;
    let m: RegExpExecArray | null;
    while ((m = GO_STRUCT_RE.exec(content))) {
      const structName = m[1]!;
      const body = m[2] ?? '';

      // Decide if this struct is a table:
      //  - sqlc file → every struct is a row type (skip if it ends in "Params"/"Row" obvious helper).
      //  - GORM     → struct has at least one field with a `gorm:` tag, OR a TableName() override.
      const hasGormTag = /gorm:"/.test(body);
      const hasTableNameOverride = tableNameMap.has(structName);
      const treatAsTable = hasGormTag || hasTableNameOverride || (isSqlc && !/(?:Params|Result)$/.test(structName));
      if (!treatAsTable) continue;

      const tableName =
        tableNameMap.get(structName) ??
        (isSqlc ? snakePlural(structName) : snakePlural(structName));
      const tableId = `table:${repoUrl}:${tableName}`;
      if (tables.some((t) => t.id === tableId)) continue;
      tables.push({
        id: tableId,
        label: 'Table',
        name: tableName,
        properties: {
          name: tableName,
          repoUrl,
          filePath: relativePath,
          sourceLine: lineOf(content, m.index),
          orm: isSqlc && !hasGormTag ? 'sqlc' : 'gorm',
          structName,
        },
      });

      GO_FIELD_RE.lastIndex = 0;
      let fm: RegExpExecArray | null;
      while ((fm = GO_FIELD_RE.exec(body))) {
        const fieldName = fm[1]!;
        const goType = fm[2]!;
        const tag = fm[3] ?? '';
        // Skip embedded gorm.Model and unexported fields (regex already caps to upper).
        if (fieldName === 'Model' && goType === 'gorm.Model') continue;
        const gormTag = extractTagValue(tag, 'gorm');
        const dbTag = extractTagValue(tag, 'db');
        const colName = parseGormColumn(gormTag) ?? dbTag ?? camelToSnake(fieldName);
        const isPrimary =
          /(^|;)primaryKey($|;|:)/i.test(gormTag ?? '') ||
          fieldName === 'ID' ||
          /:id$/i.test(colName);
        const isUnique = /(^|;)unique($|;|:)/i.test(gormTag ?? '');
        const isNotNull = /(^|;)not\s*null($|;|:)/i.test(gormTag ?? '');
        const nullable = goType.startsWith('*') ? true : !isNotNull;
        const colId = `${tableId}:${colName}`;
        columns.push({
          id: colId,
          label: 'Column',
          name: colName,
          properties: {
            tableId,
            name: colName,
            type: goType,
            nullable,
            isPrimary,
            isUnique,
            orm: isSqlc && !gormTag ? 'sqlc' : 'gorm',
            ...(fieldName !== colName ? { mappedFrom: fieldName } : {}),
          },
        });
        relations.push({
          type: 'HAS',
          sourceId: tableId,
          targetId: colId,
          confidence: 'HIGH',
          properties: { sourceLine: lineOf(content, m.index + (fm.index ?? 0)) },
        });
      }
    }

    return { tables, columns, relations };
  }
}

function extractTagValue(tag: string, key: string): string | undefined {
  const re = new RegExp(`${key}:"([^"]*)"`);
  const m = re.exec(tag);
  return m?.[1];
}

function parseGormColumn(gormTag: string | undefined): string | undefined {
  if (!gormTag) return undefined;
  const m = /(?:^|;)\s*column\s*:\s*([A-Za-z_][A-Za-z0-9_]*)/i.exec(gormTag);
  return m?.[1];
}

function camelToSnake(s: string): string {
  return s
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .replace(/([a-z\d])([A-Z])/g, '$1_$2')
    .toLowerCase();
}

function snakePlural(s: string): string {
  const snake = camelToSnake(s);
  if (/(s|x|z|ch|sh)$/.test(snake)) return `${snake}es`;
  if (/[^aeiou]y$/.test(snake)) return `${snake.slice(0, -1)}ies`;
  return `${snake}s`;
}

function lineOf(content: string, idx: number): number {
  let n = 1;
  for (let i = 0; i < idx && i < content.length; i++) {
    if (content[i] === '\n') n++;
  }
  return n;
}
