import { describe, it, expect } from 'vitest';
import { SchemaGoExtractor } from '../../src/schema.go.extractor.js';

const REPO = 'https://gitlab.com/o/r';

describe('SchemaGoExtractor', () => {
  it('extracts a GORM struct with column tag and primaryKey', () => {
    const src = [
      'package model',
      '',
      'type User struct {',
      '\tID    uint   `gorm:"primaryKey;column:id"`',
      '\tEmail string `gorm:"unique;not null;column:email"`',
      '\tName  *string `gorm:"column:name"`',
      '}',
      '',
      'func (User) TableName() string { return "users" }',
      '',
    ].join('\n');
    const r = new SchemaGoExtractor().extract(src, 'model/user.go', REPO);
    expect(r.tables.map((t) => t.name)).toEqual(['users']);
    const id = r.columns.find((c) => c.name === 'id')!;
    expect(id.properties['isPrimary']).toBe(true);
    const email = r.columns.find((c) => c.name === 'email')!;
    expect(email.properties['isUnique']).toBe(true);
    expect(email.properties['nullable']).toBe(false);
    const name = r.columns.find((c) => c.name === 'name')!;
    expect(name.properties['nullable']).toBe(true);
  });

  it('falls back to snake_plural of struct name when TableName() is absent', () => {
    const src = [
      'type Order struct {',
      '\tID  uint   `gorm:"primaryKey"`',
      '\tSku string `gorm:"unique"`',
      '}',
      '',
    ].join('\n');
    const r = new SchemaGoExtractor().extract(src, 'm.go', REPO);
    expect(r.tables.map((t) => t.name)).toEqual(['orders']);
    expect(r.columns.map((c) => c.name).sort()).toEqual(['id', 'sku']);
  });

  it('treats sqlc-generated structs as tables', () => {
    const src = [
      '// Code generated by sqlc. DO NOT EDIT.',
      'package db',
      '',
      'type Account struct {',
      '\tID    int64',
      '\tEmail string',
      '}',
      '',
      'type GetAccountParams struct {',
      '\tID int64',
      '}',
      '',
    ].join('\n');
    const r = new SchemaGoExtractor().extract(src, 'db/queries.sql.go', REPO);
    expect(r.tables.map((t) => t.name)).toEqual(['accounts']);
    expect(r.tables[0]!.properties['orm']).toBe('sqlc');
    const cols = r.columns.map((c) => c.name).sort();
    expect(cols).toEqual(['email', 'id']);
  });

  it('skips structs without gorm tags or sqlc context', () => {
    const src = 'package x\ntype Plain struct {\n\tA int\n\tB string\n}\n';
    const r = new SchemaGoExtractor().extract(src, 'x/plain.go', REPO);
    expect(r.tables).toHaveLength(0);
  });
});
